const express = require("express");
const router = express.Router();

const bimplusTokenController = require("../controllers/bimplus-token");
const verifyBimPlusToken = require("../middlewares/authentication/verifyBimPlusToken");
const verifyAccessToken = require("../middlewares/authentication/verifyToken");

/**
 * @api {get} /bimplus-token
 * @apiName Get Bimplus Token
 * @apiGroup Bimplus
 * @apiDescription  Obtain the Bimplus API Token.
 *
 * @apiHeader {String} access-token User token generated by login in.
 * @apiHeaderExample {json} Header-Example:
 *     {
 *       "Authorization": "TrackingAPI your-access-token-here"
 *     }
 *
 *
 * @apiSuccess  (Success 200) {String} message Indicates success of saving the Users location.
 * @apiSuccessExample {json} Success-Response
 *   HTTP/1.1 200 OK
 *{
 *  "message": "Successfully retrieved Bimplus Token"
 *  "token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
 *}
 */
router.get("/bimplus-token", verifyBimPlusToken, verifyAccessToken, bimplusTokenController.getToken);

module.exports = router;
